name: housing-insights
channels:
- defaults
#- gramener
dependencies:
- libpq=9.5.4
- mkl=11.3.3
- openssl=1.0.2j
- pip=8.1.2=py35_0
- psycopg2=2.7.1=py35_0
- python=3.5.2=0
- python-dateutil=2.6.1=py35_0
- pytz=2016.7=py35_0
- setuptools=27.2.0
- six=1.10.0=py35_0
- sqlalchemy=1.1.11=py35_0
- wheel=0.29.0=py35_0
- nose=1.3.7=py35_1

# These should only be used in local dev (i.e. make_draft_json), and commented out for production. Large memory requirements breaks AWS free tier. 
#- numpy=1.11.2=py35_0
#- pandas=0.19.0=np111=py35_0
# Note: Package xmljson v0.1.6 requires channel gramener ( Ref: https://anaconda.org/gramener/xmljson )
#- xmljson=0.1.6

# TODO: add pandas
- pip:
  - awscli==1.11.66
  - botocore==1.5.29
  - click==6.7
  - colorama==0.3.7
  - docutils==0.13.1
  - Flask==0.12.2
  - Flask-Cors==3.0.2
  - Flask-Restless==0.17.0
  - Flask-SQLAlchemy==2.2
  - GeoAlchemy==0.7.2
  - inflect==0.2.5
  - itsdangerous==0.24
  - Jinja2==2.9.6
  - jmespath==0.9.2
  - MarkupSafe==1.0
  - mimerender==0.6.0
  - nose==1.3.7
  - psycopg2==2.7.1
  - pyasn1==0.2.3
  - python-mimeparse==1.6.0
  - pytz==2016.7
  - PyYAML==3.12
  - requests==2.13.0
  - rsa==3.4.2
  - s3transfer==0.1.10
  - simplejson==3.10.0
  - sqlacodegen==1.1.6
  - Werkzeug==0.12.2
  - xmljson==0.1.9
