name: housing-insights
channels:
- defaults
dependencies:
- libpq=9.5.4=vc14_0
- mkl=11.3.3=1
- numpy=1.11.2=py35_0
- openssl=1.0.2j=vc14_0
- pandas=0.19.0=np111py35_0
- pip=8.1.2=py35_0
- psycopg2=2.6.2=py35_0
- python=3.5.2=0
- python-dateutil=2.5.3=py35_0
- pytz=2016.7=py35_0
- setuptools=27.2.0=py35_1
- six=1.10.0=py35_0
- sqlalchemy=1.1.3=py35_0
- vc=14=0
- vs2015_runtime=14.0.25123=0
- wheel=0.29.0=py35_0
- pip:
  - awscli==1.11.66
  - botocore==1.5.29
  - colorama==0.3.7
  - docutils==0.13.1
  - jmespath==0.9.2
  - pyasn1==0.2.3
  - pyyaml==3.12
  - requests==2.13.0
  - rsa==3.4.2
  - s3transfer==0.1.10


