
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CTDC Project
email: neal@nhumphrey.com
description: > # this means to ignore newlines until "baseurl:"
  This is the placeholder website for the CTDC project.
baseurl:  # the subpath of your site, e.g. /blog
tagline: Bringing open data to affordable housing decision makers

# TODO - figure out how to use the 'baseurl' variable within this file itself, to have better logo url paths.
partners: [{name: 'CNHED', logo: '/assets/CNHED-logo.jpg',  url: 'https://www.cnhed.org/' },{  name: 'Urban Institute (Neighborhood Info DC)',  logo: '/assets/urban-logo.jpg',  url: 'http://www.neighborhoodinfodc.org/'  },{  name: 'Living Cities (Civic Tech and Data Collaborative)',  logo: '/assets/LC-logo.jpg',  url: 'https://www.livingcities.org/work/civic-tech-and-data-collaborative'  },{  name: 'DC Department of Housing and Community Development',  logo: '/assets/dhcd-logo.jpg', url: 'http://dhcd.dc.gov/'  }]

# Build settings
markdown: kramdown
encoding: UTF-8
